[profile.default]
src = "src"
out = "out"
libs = ["lib","node_modules"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
[etherscan]
polygon-amoy = { key = "${API_KEY}", url = "https://api-amoy.polygonscan.com/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
